export const categories = [
    "TECH_AND_GADGETS",
    "PRODUCTIVITY",
    "GAMING",
    "CREATIVE_WORKSPACE",
    "STUDY_SPACE",
    "HOME_OFFICE",
    "DIY_AND_CUSTOM_SETUPS",
    "MINIMALIST",
    "COZY_SPACES",
    "COLLABORATIVE_WORKSPACES",
    "OTHERS",
];
